### ISSUE TITLE
RE4 Save Utility

### ISSUE THREAD

**Issue by Wchartr1** [NathanJRollins/re4-save-reattribution-utility#1]
I have tried using this utility with Resident Evil Revelations 2 (it should work with this game and not just RE4, right?), but your utility will not recognize the DAT file when I try to upload.  If you're sure the tool will only work with RE4, please contact me ASAP at wyattchartrand@gmail.com.  I desperately need full 100% save data to work on Steam for that game and two others (Rev1 and RE Remake) by this August.

**Comment by NathanJRollins** [comment]
@Wchartr1 Hi!  This utility definitely only works with Steam's HD version of RE4.  If it worked for any other game at all ever, I'd be very surprised, heh - I 100% wouldn't expect it to work with any others.  RE-REV, RE-REV2, and RE-Re probably use very different save formats, which I'd expect are much less simple & easily modifiable, so an approach as naive as this tool's technique would probably end in failure.  I'm not saying it can't be done, but this tool definitely can't do it, and I wouldn't know how to either.  Good luck though brother, & godspeed (:
